--return {'NTBBloodbath/doom-one.nvim',priority = 1000,}
return {"folke/tokyonight.nvim", priority = 1000}
--return{ "ellisonleao/gruvbox.nvim", priority = 1000}
--return{
--  "navarasu/onedark.nvim",
--  priority = 1000, -- make sure to load this before all the other start plugins
--  config = function()
--    require('onedark').setup {
--      style = 'darker'
--    }
--    require('onedark').load()
--  end
--}
